POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
  "username":"demo1",
  "email": "demo1@gmail.com",
  "password":"123456"
}

####

POST http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "password":"123456"
}

####

POST http://localhost:5000/posts/ HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "title":"blog demo 6",
  "desc":"demo blog dec goes here..."
}

####

POST https://mernblogu.herokuapp.com/auth/register HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "email": "demo@gmail.com",
  "password":"123456"
}

####

POST https://mernblogu.herokuapp.com/auth/login HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "password":"123456"
}

####

POST https://mernblogu.herokuapp.com/posts/ HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "title":"blog demo",
  "desc":"demo blog dec goes here..."
}