POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
  "username":"demo23",
  "email": "demo22@gmail.com",
  "password":"123456"
}

####

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
  "username":"goku1",
  "password":"123"
}

####

POST http://localhost:5000/api/posts/ HTTP/1.1
content-type: application/json

{
  "username":"demo23",
  "title":"blog test demddo 12",
  "desc":"demo blog dec goes here..."
}

####

POST https://mernblogu.herokuapp.com/api/auth/register HTTP/1.1
content-type: application/json

{
  "username":"de14",
  "email": "dem4os4@gmail.com",
  "password":"123456"
}

####

POST https://mernblogu.herokuapp.com/api/auth/login HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "password":"123456"
}

####

POST https://mernblogu.herokuapp.com/api/posts/ HTTP/1.1
content-type: application/json

{
  "username":"demo",
  "title":"blog demo",
  "desc":"demo blog dec goes here..."
}